save，Fa鸽版
Uni-Gal/UniGal-Script pull request #8
Opened 2021-03-05 14:47 UTC by Akarinnnnn

字面意思

2021-03-11 13:47 UTC, LaoshuBaby commented
原有的save和archive废止并以新的Fa版save代替
确实可以
并且其中对于云存档和auto等抽象也较好
但是其中有一些问题需要指出
接下将逐个讨论

2021-03-11 13:51 UTC, LaoshuBaby commented
```
+ 1001. save_auto  
+ 1002. save_at，示例`<save_at page="autosave" slot="1" />`  
+ 1003. save_pushcloud，示例`<save_pushcloud timeout="2000ms" />`  
+ 1004. save_pullcloud，示例`<save_pullcloud timeout="2000ms" />`  
```

上述为Fa鸽提出的新的save函数

但，私以为有三点尚且未能体现

**一个是**是否禁止存档，这个可能要和之前的“尽量避免明显的引入状态”这个原则相违背，但是如何考虑不放弃这个特性，或重新对该特性进行描述？

```
+ 1032. archive_forbidden
```

**另一个**是，有写就有读，读操作的抽象，是否是简单直接换save为load就可以，若可，可简单描述一下相关定义

**第三个**是，删除的操作不应被忽视

```
+ 1034. archive_delete
```

以上

2021-03-11 14:09 UTC, LaoshuBaby reviewed
我今天就只说三件事

save status

load

delete

2021-03-11 14:09 UTC, LaoshuBaby requested changes
我今天就只说三件事

save status

load

delete

2021-03-11 14:13 UTC, Akarinnnnn commented
1. 忽视状态，存档随时可以以编程方式触发，失败无提示
2. 不宜通过编程方式加载存档
3. 不宜直接清空存档，这属于我所提到的“阴间操作”，确实有需求建议转extension

2021-03-12 09:05 UTC, Akarinnnnn commented
补充昨天的解释  
save status、load、delete应该移动到 反对使用区的元游戏拓展专项（deprecated.metaext），正常向的文字冒险用不到，也不应该使用这些来破坏游戏体验

2021-03-12 09:07 UTC, LaoshuBaby commented
可，所以快去移动到dangerzone/其他能表示反对和危险的条目里面去吧（o(*￣▽￣*)ブ




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月12日(星期五) 下午5:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Uni-Gal/UniGal-Script] save，Fa鸽版 (#8)





 
补充昨天的解释
 save status、load、delete应该移动到 反对使用区的元游戏拓展专项（deprecated.metaext），正常向的文字冒险用不到，也不应该使用这些来破坏游戏体验
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-04-12 14:02 UTC, merged